# Generated by Django 2.0.6 on 2018-06-28 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('excerpt', models.TextField(verbose_name='摘要')),
                ('content', models.TextField(verbose_name='正文')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('file', models.CharField(max_length=100, verbose_name='文件')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-date'],
            },
        ),
    ]
