# Generated by Django 2.0.6 on 2018-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='歌曲')),
                ('artist', models.CharField(max_length=50, verbose_name='歌手')),
                ('album', models.CharField(max_length=50, verbose_name='专辑')),
                ('album_type', models.CharField(choices=[('album', '专辑'), ('ep', 'EP'), ('single', '单曲')], default='album', max_length=10, verbose_name='专辑类型')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年份')),
                ('album_cover', models.CharField(max_length=50, verbose_name='专辑封面')),
                ('lyric', models.CharField(max_length=50, verbose_name='歌词')),
                ('source', models.CharField(max_length=50, verbose_name='歌曲')),
                ('source_type', models.CharField(choices=[('apple_music', 'Apple Music'), ('netease_cloud_music', '网易云音乐')], default='apple_music', max_length=20, verbose_name='歌曲来源')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
                'ordering': ['-time'],
            },
        ),
    ]
