# Generated by Django 2.0.6 on 2018-07-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=50, verbose_name='主歌手'),
        ),
        migrations.AlterField(
            model_name='music',
            name='source',
            field=models.CharField(max_length=50, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='music',
            name='source_type',
            field=models.CharField(choices=[('apple_music', 'Apple Music'), ('netease_cloud_music', '网易云音乐')], default='apple_music', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
