# Generated by Django 2.0.6 on 2018-07-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180704_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artist_featured',
            field=models.CharField(default='null', max_length=50, verbose_name='助阵歌手'),
        ),
    ]
