# Generated by Django 2.0.6 on 2018-07-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_artist_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist_featured',
            field=models.CharField(max_length=50, verbose_name='助阵歌手'),
        ),
    ]
