# Generated by Django 2.0.6 on 2018-07-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20180704_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='artist',
            new_name='artist_lead',
        ),
    ]
