# Generated by Django 2.0.6 on 2018-07-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180704_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist_featured',
            field=models.CharField(blank=True, max_length=50, verbose_name='助阵歌手'),
        ),
    ]
