# Generated by Django 2.0.6 on 2018-07-05 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20180704_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='annual',
            field=models.BooleanField(default=False, verbose_name='年度'),
        ),
        migrations.AddField(
            model_name='music',
            name='like_in',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2018)], verbose_name='在哪一年喜欢'),
        ),
        migrations.AlterField(
            model_name='music',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2019)], verbose_name='年份'),
        ),
    ]
