# Generated by Django 2.0.6 on 2018-07-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20180711_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='lyric',
        ),
        migrations.AddField(
            model_name='music',
            name='genius',
            field=models.CharField(blank=True, max_length=50, verbose_name='Genius'),
        ),
    ]
