# Generated by Django 2.0.6 on 2018-07-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20180711_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='source',
        ),
        migrations.RemoveField(
            model_name='music',
            name='source_type',
        ),
        migrations.AddField(
            model_name='music',
            name='apple_music',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apple Music'),
        ),
        migrations.AddField(
            model_name='music',
            name='netease_cloud_music',
            field=models.CharField(blank=True, max_length=100, verbose_name='网易云音乐'),
        ),
        migrations.AddField(
            model_name='music',
            name='qq_music',
            field=models.CharField(blank=True, max_length=100, verbose_name='QQ 音乐'),
        ),
        migrations.AddField(
            model_name='music',
            name='spotify',
            field=models.CharField(blank=True, max_length=100, verbose_name='Spotify'),
        ),
        migrations.AlterField(
            model_name='music',
            name='album_cover',
            field=models.CharField(max_length=100, verbose_name='专辑封面'),
        ),
        migrations.AlterField(
            model_name='music',
            name='genius',
            field=models.CharField(blank=True, max_length=100, verbose_name='Genius'),
        ),
    ]
