# Generated by Django 2.0.6 on 2018-07-12 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20180711_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='artist_lead',
            new_name='artist',
        ),
    ]
