# Generated by Django 2.0.6 on 2018-07-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20180712_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist_featured',
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.CharField(max_length=100, verbose_name='专辑'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=100, verbose_name='歌手'),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
