# Generated by Django 2.0.6 on 2018-07-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_music_you_tube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='you_tube',
            new_name='youtube',
        ),
    ]
