# Generated by Django 2.0.6 on 2018-07-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20180713_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='apple_music',
        ),
        migrations.RemoveField(
            model_name='music',
            name='qq_music',
        ),
        migrations.RemoveField(
            model_name='music',
            name='spotify',
        ),
        migrations.RemoveField(
            model_name='music',
            name='youtube',
        ),
    ]
