# Generated by Django 2.0.6 on 2018-07-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20180716_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
