# Generated by Django 2.0.6 on 2018-08-02 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20180716_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
    ]
