# Generated by Django 2.0.6 on 2019-04-30 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_auto_20180802_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2038)], verbose_name='年份'),
        ),
    ]
