# Generated by Django 2.0.6 on 2019-04-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_auto_20190430_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='genius',
        ),
    ]
