# Generated by Django 2.0.6 on 2019-04-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_remove_music_genius'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='album_cover',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='netease_cloud_music',
            new_name='link',
        ),
    ]
