# Generated by Django 2.2.11 on 2020-03-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_auto_20200206_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='essential',
        ),
    ]
