# Generated by Django 2.2.11 on 2020-03-28 11:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.time


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_remove_music_essential'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='essential',
            field=models.BooleanField(default=False, verbose_name='精选'),
        ),
        migrations.AlterField(
            model_name='music',
            name='year',
            field=models.PositiveSmallIntegerField(default=utils.time.current_year, verbose_name='年份'),
        ),
        migrations.CreateModel(
            name='AnnualSummary',
            fields=[
                ('year', models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')),
                ('song_of_this_year_color', models.CharField(default='#', max_length=7, validators=[django.core.validators.MaxLengthValidator(7)], verbose_name='年度歌曲颜色')),
                ('song_of_this_year_lyric', models.CharField(max_length=100, verbose_name='年度歌曲歌词')),
                ('song_of_this_year_link_apple_music', models.CharField(max_length=100, verbose_name='年度歌曲 Apple Music 链接')),
                ('song_of_this_year_link_spotify', models.CharField(max_length=100, verbose_name='年度歌曲 Spotify 链接')),
                ('song_of_this_year_link_youtube', models.CharField(blank=True, max_length=100, verbose_name='年度歌曲 YouTube 链接')),
                ('essentials_color', models.CharField(default='#', max_length=7, validators=[django.core.validators.MaxLengthValidator(7)], verbose_name='精选集颜色')),
                ('essentials_link_apple_music', models.CharField(max_length=100, verbose_name='精选集 Apple Music 链接')),
                ('essentials_link_spotify', models.CharField(max_length=100, verbose_name='精选集 Spotify 链接')),
                ('essentials_intro', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='精选集 Intro')),
                ('essentials_outro', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='精选集 Outro')),
                ('essentials_track_1', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='精选集 Track 1')),
                ('essentials_track_10', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='精选集 Track 10')),
                ('essentials_track_2', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='精选集 Track 2')),
                ('essentials_track_3', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='精选集 Track 3')),
                ('essentials_track_4', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='精选集 Track 4')),
                ('essentials_track_5', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='精选集 Track 5')),
                ('essentials_track_6', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='精选集 Track 6')),
                ('essentials_track_7', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='精选集 Track 7')),
                ('essentials_track_8', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='精选集 Track 8')),
                ('essentials_track_9', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='精选集 Track 9')),
                ('song_of_this_year', models.ForeignKey(limit_choices_to={'essential': True, 'time__year': models.PositiveSmallIntegerField(default=utils.time.current_year, primary_key=True, serialize=False, verbose_name='年份')}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.Music', verbose_name='年度歌曲')),
            ],
            options={
                'verbose_name': '年度总结',
                'verbose_name_plural': '年度总结',
                'ordering': ['-year'],
            },
        ),
    ]
