# Generated by Django 2.2.11 on 2020-03-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_auto_20200328_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Song',
        ),
    ]
