# Generated by Django 2.2.11 on 2020-03-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_auto_20200328_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-time'], 'verbose_name': '歌曲', 'verbose_name_plural': '歌曲'},
        ),
    ]
