# Generated by Django 2.2.11 on 2020-03-29 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_auto_20200329_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualsummary',
            name='essentials_color',
            field=models.CharField(max_length=6, validators=[django.core.validators.MaxLengthValidator(6)], verbose_name='精选集颜色'),
        ),
        migrations.AlterField(
            model_name='annualsummary',
            name='song_of_this_year_color',
            field=models.CharField(max_length=6, validators=[django.core.validators.MaxLengthValidator(6)], verbose_name='年度歌曲颜色'),
        ),
    ]
