# Generated by Django 2.2.11 on 2020-04-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0035_auto_20200329_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.IntegerField(verbose_name='年份'),
        ),
    ]
