# Generated by Django 2.2.17 on 2021-02-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0036_auto_20200402_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
