# Generated by Django 2.2.11 on 2020-04-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='label',
        ),
    ]
