# Generated by Django 2.2.11 on 2020-04-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200413_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新于'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建于'),
        ),
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(max_length=100, verbose_name='标签'),
        ),
    ]
